env:
  browser: true
  commonjs: true
  es2021: true
  node: true
extends:
  - airbnb-base
settings:
  import/core-modules: [electron]
globals: { "MAIN_WINDOW_WEBPACK_ENTRY": true }
parserOptions:
  ecmaVersion: 12
rules: {
    "global-require": "off",
    "no-unused-vars": "off",
    "no-useless-constructor": "off",
    "class-methods-use-this": "off",
    "no-plusplus": "off",
    "no-undef": "off",
    "no-param-reassign": "off",
    "no-else-return": "off",
    "prefer-arrow-callback": "off",
    "no-restricted-syntax": "off",
    "no-use-before-define": "off",
    "no-lonely-if": "off",
    "import/no-useless-path-segments": "off",
    "no-shadow": "off",
    "no-alert": "off",
    # TODO: reenable this one in the future, when the application uses a more
    # modern JS architecture. It's needed r/n so that stuff like "location"
    # and "window" are usable
    "no-restricted-globals": "off",
    # TODO: also reenable this, probably. We only use it so that we can
    # dynamically load a file in savesession.js, and in the future we should
    # do this using Electron's file APIs
    "import/no-dynamic-require": "off",
    # The following are some rules where prettier and eslint (or at least the
    # Airbnb settings for eslint) disagree, as of writing. To make life easier,
    # we just delegate to prettier for most of these (so even though the Airbnb
    # rules say to use single quotes, we override that here).
    "quotes": ["error", "double"],
    "comma-dangle": "off",
    "operator-linebreak": "off",
    "implicit-arrow-linebreak": "off",
    "object-curly-newline": "off",
  }
